kinopoisk:
  tokens:
  - aaa

bean:
  visualizer:
    web-path: /beans

# Настройка файла для spring-batch
file:
  input: C:\Users\KAfanasiev\Desktop\Study\movie-match\movie-match-api\src\main\resources\movies.data\movies.csv