spring:
  application:
    name: movie-match
  datasource:
    hikari:
      schema: public
    url: jdbc:postgresql://localhost:12200/movie_db
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  config:
    import: optional:configserver:http://user:password@localhost:8888/
  cloud:
    config:
      label: master

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
#         refresh context: curl -H "Content-Type: application/json" -d {} http://localhost:8081/actuator/refresh
        include: "*"

# Не работает сваггер из-за переименования с MovieMatch на movie-match (надо пересоздать проект)